FROM node:20-alpine
RUN apk add --no-cache libc6-compat
RUN apk update
RUN corepack enable && corepack prepare yarn@1.22.22 --activate 
WORKDIR /app

# Install turbo globally
RUN yarn global add turbo

# Copy only what's needed for package installation
COPY package.json yarn.lock turbo.json ./
COPY apps/dtcv/package.json ./apps/dtcv/package.json
COPY packages/viewport/package.json ./packages/viewport/package.json

# Install dependencies with frozen lockfile
RUN yarn install --frozen-lockfile

# Then copy the rest of the files
COPY . .

# Start only the web app in development mode
CMD ["yarn", "workspace", "dtcv", "dev"]