networks:
  dtcv-platform:
    external: true
    name: supabase_network_dtcv-platform

services:
  redis:
    image: 'redis:7-alpine'
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./volumes/redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks: ['dtcv-platform']
  minio:
    image: 'minio/minio'
    command: server --console-address ":9001" /data
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - ./volumes/storage:/data:z
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 2s
      timeout: 10s
      retries: 5
    networks: ['dtcv-platform']

  minio-createbucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
      MINIO_BUCKET: ${S3_BUCKET}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set storage http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mb storage/$${MINIO_BUCKET};
      exit 0;
      "
    networks: ['dtcv-platform']
