name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main
    paths:
      - packages/**/*.ts
  push:
    branches:
      - main
      - development
    paths:
      - packages/**/*.ts

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Git config"
      run: |
        git config user.name "github actions bot"
        git config user.email "<>"

    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: "Publish"
      run: |
        if [ ${{ github.base_ref }} = development ]; then
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          npx lerna version --conventional-commits --conventional-graduate --yes
        fi

        npx lerna publish from-git --yes
